module.exports = {
  someSidebar: [
    'introduction', {
      '1. Começando a Jogar': [
        '1-starting-the-game/what-is',
        '1-starting-the-game/players-role',
        '1-starting-the-game/gm-role',
        '1-starting-the-game/how-to-play'
      ],
      '2. Criando seu Personagem': [
        '2-sheet-creation/getting-sheet',
        '2-sheet-creation/pick-a-name',
        '2-sheet-creation/pick-a-role',
        '2-sheet-creation/money',
        '2-sheet-creation/initial-level',
        '2-sheet-creation/define-your-culture',
        '2-sheet-creation/defining-attributes',
        '2-sheet-creation/movement-points',
        '2-sheet-creation/armor-deduction',
        '2-sheet-creation/hp-points',
        '2-sheet-creation/mp-points',
        '2-sheet-creation/defense-points',
        '2-sheet-creation/magic-defense',
        '2-sheet-creation/attack-points',
        '2-sheet-creation/magic-attack-points',
        '2-sheet-creation/initial-items',
        '2-sheet-creation/grimos-and-magic',
        '2-sheet-creation/defining-your-origins',
        '2-sheet-creation/defining-initiative'
      ],
      '3. Espécies Jogáveis': [
        '3-species/species-introduction',
        '3-species/specie-goblins',
        '3-species/specie-armadons',
        '3-species/specie-metaloids',
        '3-species/specie-razalans',
        '3-species/specie-valdaris',
        '3-species/specie-luminins'
      ],
      '4. Grimos': [
        '4-grimos-and-spells/grimos-introduction',
        '4-grimos-and-spells/giurads-crest',
        '4-grimos-and-spells/lunns-jewel',
        '4-grimos-and-spells/alluras-orb',
        '4-grimos-and-spells/eye-of-kanus',
        {
          '[Em desenvolvimento]': [
            '4-grimos-and-spells/ark-of-ravna',
            '4-grimos-and-spells/darians-totem',
            '4-grimos-and-spells/flask-of-valari',
            '4-grimos-and-spells/magni-machine',
            '4-grimos-and-spells/rune-of-ixin',
          ]
        }
      ],
      '5. Papéis de Jogo': [
        '5-roles/roles-introduction',
        '5-roles/roles-adventurer',
        '5-roles/roles-tank',
        '5-roles/roles-hunter',
        '5-roles/roles-arcanist',
        '5-roles/roles-priest',
        '5-roles/roles-fortuner'
      ],
      '6. Culturas': [
        '6-cultures/cultures-introduction',
        '6-cultures/children-of-dew',
        '6-cultures/children-of-sands',
        '6-cultures/children-of-sailing',
        '6-cultures/children-of-clouds',
        '6-cultures/children-of-islands',
        '6-cultures/children-of-underground',
        '6-cultures/children-of-storms',
        '6-cultures/children-of-plains',
        '6-cultures/children-of-mountains',
        '6-cultures/children-of-depths',
      ],
      '7. Regras do Jogo': [
        '7-game-rules/rules-introduction',
        '7-game-rules/scenes',
        '7-game-rules/declaring-actions-and-outcomes',
        '7-game-rules/skill-checks',
        '7-game-rules/challenge-checks',
        '7-game-rules/short-and-long-rest',
        '7-game-rules/merchants',
        '7-game-rules/blacksmiths',
        '7-game-rules/terrain',
        '7-game-rules/evolving',
        '7-game-rules/game-etiquette',
      ],
      '8. Sistema 2d20': [
        '8-system-2d20/system-introduction',
        '8-system-2d20/critical-outcomes',
        '8-system-2d20/epic-outcomes',
        '8-system-2d20/matching-outcomes',
        '8-system-2d20/nulled-outcomes',
        '8-system-2d20/advantage-rolls',
      ],
      '9. Regras  de Combate': [
        '9-combat-rules/combat-intro',
        '9-combat-rules/begining-of-combat',
        '9-combat-rules/player-turn',
        '9-combat-rules/moving',
        '9-combat-rules/understanding-magic-spells',
        '9-combat-rules/physical-combat',
        '9-combat-rules/magical-combat',
        '9-combat-rules/death',
        '9-combat-rules/durability',
        '9-combat-rules/negative-effects',
      ],
      '10. Narrador': [
        '10-the-guide/guide-intro',
        '10-the-guide/fundamentals',
        '10-the-guide/structure-history',
        '10-the-guide/create-the-world',
        '10-the-guide/inhabit-the-world',
        '10-the-guide/preparing-a-session',
        '10-the-guide/preparing-combats',
        '10-the-guide/get-in-the-mood',
        '10-the-guide/tell-the-tale',
        '10-the-guide/game-tips',
        '10-the-guide/gm-toolbelt',
      ],
      '11. A Magia': [
        '11-the-magic/magic-in-the-world',
        '11-the-magic/magic-potions',
        '11-the-magic/radamagi-and-scrolls',
        '11-the-magic/magic-items',
        '11-the-magic/grimos',
        '11-the-magic/nexus-master',
        '11-the-magic/the-cycle-of-life',
        '11-the-magic/zigonio-fragments',
        '11-the-magic/zigonio-gems',
        '11-the-magic/gem-cards',
        '11-the-magic/grimo-popularization'
      ],
      '12. As Terras Místicas': [
        '12-the-world/wheres-the-game-placed',
        '12-the-world/the-blackout',
        '12-the-world/the-emotions-and-the-blackout',
        '12-the-world/the-society-and-the-blackout',
        '12-the-world/the-economy-and-the-blackout',
        '12-the-world/the-magic-and-the-blackout',
        '12-the-world/the-magic-and-the-origin-of-the-world',
        '12-the-world/the-auguries',
        '12-the-world/the-continents',
        '12-the-world/class-academies',
        '12-the-world/the-protectorship-order',
        '12-the-world/the-ecos',
        '12-the-world/the-ages-of-the-world'
      ],
      '13. Appêndice': [
        '13-appendix/stereotypes',
        '13-appendix/flaws',
        '13-appendix/character-sheet',
        '13-appendix/types-of-armor',
        '13-appendix/modifier-rule'
      ]
    }
  ]
};
